# PostgreSQL target database (application user credentials)
postgres:
  host: imperium-pg-rw
  port: 5432
  database: imperium
  appUser: "imperium"
  appPassword: "imperium-secret"

# Kafka cluster bootstrap
kafka:
  bootstrapServers: "imperium-kafka-kafka-bootstrap:9092"

# Name of the KafkaConnect cluster resource
connect:
  clusterName: "imperium-streaming-news-processing-kafka-connect"

# Country Sink configuration
countriesSink:
  enabled: false
  name: imperium-countries-sink-v2
  tasksMax: 1

# Language Sink configuration
languagesSink:
  enabled: false
  name: imperium-languages-sink
  tasksMax: 1

# Authority Sink configuration
authoritiesSink:
  enabled: false
  name: imperium-authorities-sink
  tasksMax: 1

# Rubric Sink configuration
rubricsSink:
  enabled: false
  name: imperium-rubrics-sink
  tasksMax: 1

# Sedition Sink configuration
seditionsSink:
  enabled: false
  name: imperium-seditions-sink
  tasksMax: 1

# Link Sink configuration
linksSink:
  enabled: false
  name: imperium-links-sink
  tasksMax: 1
