replicaCount: 1

image:
  repository: registry.registry.svc.cluster.local:5000/imperium-redis-projector
  pullPolicy: IfNotPresent
  tag: "1.0.0"

env:
  - name: KAFKA_BOOTSTRAP_SERVERS
    value: "imperium-kafka-kafka-bootstrap:9092"
  - name: SCHEMA_REGISTRY_URL
    value: "http://imperium-streaming-news-processing-schema-registry:8081"
  - name: REDIS_URL
    value: "redis://imperium-streaming-news-processing-redis:6379/0"
  - name: KAFKA_GROUP_ID
    value: "imperium-redis-projector-group"
