replicaCount: 1

image:
  repository: registry.registry.svc.cluster.local:5000/llama-cpp-gemma
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8080

model:
  filename: embeddinggemma-300M-Q8_0.gguf

config:
  threads: 32
  threadsBatch: 32
  batchSize: 8192
  ubatchSize: 2048

resources:
  limits:
    cpu: "8"
    memory: 4Gi
  requests:
    cpu: "8"
    memory: 2Gi


nodeSelector: {}
tolerations: []
affinity: {}
