apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pgadmin.fullname" . }}-servers
  labels:
    {{- include "pgadmin.labels" . | nindent 4 }}
data:
  servers.json: |
    {
      "Servers": {
        "1": {
          "Name": {{ .Values.pgConnection.name | quote }},
          "Group": "Servers",
          "Host": {{ .Values.pgConnection.host | quote }},
          "Port": {{ .Values.pgConnection.port }},
          "MaintenanceDB": {{ .Values.pgConnection.db | quote }},
          "Username": {{ .Values.pgConnection.user | quote }},
          "SSLMode": "prefer"
        }
      }
    }
