apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pgadmin.fullname" . }}
  labels:
    {{- include "pgadmin.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "pgadmin.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "pgadmin.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
            - name: PGADMIN_DEFAULT_EMAIL
              value: {{ .Values.env.email | quote }}
            - name: PGADMIN_DEFAULT_PASSWORD
              value: {{ .Values.env.password | quote }}
            - name: PGADMIN_SERVER_JSON_FILE
              value: "/pgadmin4/servers.json"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: servers-config
              mountPath: "/pgadmin4/servers.json"
              subPath: "servers.json"
              readOnly: true
      volumes:
        - name: servers-config
          configMap:
            name: {{ include "pgadmin.fullname" . }}-servers
