apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "imperium-frontend.fullname" . }}
  labels:
    {{- include "imperium-frontend.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "imperium-frontend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "imperium-frontend.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            {{- range $key, $val := .Values.config }}
            - name: {{ $key }}
              value: {{ $val | quote }}
            {{- end }}
