apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-debezium-creds
  labels:
    {{- include "kafka-connect-connectors.labels" . | nindent 4 }}
type: Opaque
stringData:
  password: {{ .Values.postgres.password | quote }}
