apiVersion: kafka.strimzi.io/v1
kind: KafkaConnect
metadata:
  name: {{ include "kafka-connect.fullname" . }}
  labels:
    {{- include "kafka-connect.labels" . | nindent 4 }}
  annotations:
    strimzi.io/use-connector-resources: "true"
spec:
  version: {{ .Values.kafka.version | quote }}
  image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
  replicas: {{ .Values.replicaCount }}
  bootstrapServers: {{ .Values.kafka.bootstrapServers | quote }}
  groupId: {{ .Values.config.groupId | quote }}
  offsetStorageTopic: {{ .Values.config.offsetStorageTopic | quote }}
  configStorageTopic: {{ .Values.config.configStorageTopic | quote }}
  statusStorageTopic: {{ .Values.config.statusStorageTopic | quote }}
  config:
    offset.storage.replication.factor: 1
    config.storage.replication.factor: 1
    status.storage.replication.factor: 1
    key.converter: org.apache.kafka.connect.storage.StringConverter
    value.converter: io.confluent.connect.avro.AvroConverter
    value.converter.schema.registry.url: {{ .Values.config.schemaRegistryUrl | quote }}
  {{- if .Values.otel.enabled }}
  template:
    connectContainer:
      env:
        - name: KAFKA_OPTS
          value: "-javaagent:/otel/otel-javaagent.jar"
        - name: OTEL_SERVICE_NAME
          value: "kafka-connect"
        - name: OTEL_TRACES_EXPORTER
          value: "otlp"
        - name: OTEL_METRICS_EXPORTER
          value: "otlp"
        - name: OTEL_EXPORTER_OTLP_PROTOCOL
          value: "grpc"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: {{ .Values.otel.collectorEndpoint | quote }}

  {{- end }}

