# Default values for imperium-streaming-news-processing.
# This is an umbrella chart. Values for sub-charts can be configured here.
#
# Example:
# sub-chart-name:
#   key: value

strimzi-kafka-operator:
  createGlobalResources: false

kafka-cluster:
  enabled: true

UI:
  enabled: true
  kafka-ui:
    kafka:
      schemaRegistry: "http://imperium-streaming-news-processing-schema-registry:8081"

schema-registry:
  enabled: true
  kafka:
    bootstrapServers: "imperium-kafka-kafka-bootstrap:9092"

kafka-connect:
  enabled: true
  replicaCount: 1
  image:
    repository: "registry.registry.svc.cluster.local:5000/debezium-avro"
    tag: "1.1.2"
  kafka:
    bootstrapServers: "imperium-kafka-kafka-bootstrap:9092"
  config:
    schemaRegistryUrl: "http://imperium-streaming-news-processing-schema-registry:8081"


